---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: sealed-secrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sealed-secrets
  namespace: sealed-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: sarathy-sealing-keys
    creationPolicy: Owner
    template:
      type: kubernetes.io/tls
      metadata:
        labels:
          sealedsecrets.bitnami.com/sealed-secrets-key: active
  data:
  - secretKey: tls.crt
    remoteRef:
      key: sealed-secrets-sealing-crt	
  - secretKey: tls.key
    remoteRef:
      key: sealed-secrets-sealing-key	
