---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: local-source
  namespace: flux-system
spec:
  interval: 30s
  path: ./crossplane
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client

