---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - aws-provider.yaml
  - aws-providerconfig.yaml


#
# Previously, the AWS credentials of an IAM user were made available to the Crossplane AWS Provider using a Kubernetes Secret
# The Kubernetes Secret was deployed using a SealedSecret resource.
# We needed Bitnami's SealedSecrets Controller to unseal the SealedSecret into a Secret.
# This is no longer needed after making the Crossplane AWS Provider run under IRSA.
#
# ---
# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
# resources:
#   - sealed-secrets-controller.yaml
#   - aws-provider.yaml
