---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: crossplane-composite-resources
  namespace: flux-system
spec:
  dependsOn:
  - name: crossplane-configuration-package
  interval: 30s
  path: ./deploy/management/crossplane-xr
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
  - kind: Secret
    apiVersion: v1
    name: configuration-prod-eks-cluster
    namespace: flux-system
  - kind: OpenIDConnectProvider
    apiVersion: iam.aws.crossplane.io/v1beta1
    name: oidc-idp-prod-eks-cluster
  validation: client

