---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: crossplane-k8s-provider-package
  namespace: flux-system
spec:
  dependsOn:
  - name: crossplane-aws-provider-package
  interval: 30s
  path: ./deploy/management/crossplane-k8s-provider
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
  - kind: Deployment
    name: provider-kubernetes-13b4626ee34c
    namespace: crossplane-system    
  validation: client
  timeout: 2m

