#
# This deployment manigest is not relevant anymore
# Workloads that are to be deployed on a workloads cluster are synced to the latter using Flux that is installed on the respective workload cluster
# Flux gets installed on the workload cluster by using Flux that runs on the management cluster using Flux's remote deployment capability
#
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: application-webapp
  namespace: flux-system
spec:
  interval: 30s
  path: ./deploy/webapp
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  kubeConfig:
    secretRef:
      name: crossplane-workload-cluster-connection
  validation: client
