---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - aws-providerconfig.yaml
  - crossplane-eks-composition.yaml



# ---
# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
# resources:
#   - aws-credentials-sealed.yaml
#   - aws-providerconfig.yaml
#   - crossplane-eks-composition.yaml
