---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: crossplane-repository
  namespace: crossplane-system
spec:
  interval: 5m
  url: https://charts.crossplane.io/stable