---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: k8s-config
spec:
  podSecurityContext:
    fsGroup: 2000
  args:
  - '--debug'

---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-kubernetes
spec:
  package: 937351930975.dkr.ecr.us-east-1.amazonaws.com/crossplane-k8s-provider:v0.4.1
  controllerConfigRef:
    name: k8s-config