---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: k8s-config
spec:
  podSecurityContext:
    fsGroup: 2000
  args:
  - '--debug'

---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-kubernetes
spec:
  package: "public.ecr.aws/awsvijisarathy/crossplane-k8s-provider:main"
  controllerConfigRef:
    name: k8s-config