---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - aws-provider.yaml



# ---
# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
# resources:
#   - sealed-secrets-controller.yaml
#   - aws-provider.yaml
